env:
  browser: true
  es2021: true
extends: airbnb
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  quotes: off
  "no-param-reassign": off
  "no-undef": off
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
  "import/order": off
  "react/function-component-definition": off 
  "jsx-a11y/anchor-is-valid": off
  "comma-dangle": off

  "arrow-body-style": off